x-common: 
  deunhealth:
    &deunhealth
    labels:
      - "deunhealth.restart.on.unhealthy=true"
  default:
    &default
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    restart: unless-stopped

services:


  wings:
    <<: [*default, *deunhealth]
    container_name: wings
    image: ghcr.io/pterodactyl/wings:v1.11.13
    env_file:
      - .env
    restart: always
    networks:
      - pterodactyl
      - pterodactyl_nw
    ports:
      - "8080:80"
      - "8443:443"
      - "2022:2022"
    tty: true
    environment:
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "${DOCKER_SOCK}:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "${CONFIG_PTERODACTYL_PATH}/wings/etc/:/etc/pterodactyl/"
      - "${CONFIG_PTERODACTYL_PATH}/wings/logs:/var/log/pterodactyl/"
      - "${SERVERS_DATA_FULL_PATH}:${SERVERS_DATA_FULL_PATH}"

networks:
  pterodactyl:
    external: true
  pterodactyl_nw:
    external: true