background: 
  image: "https://raw.githubusercontent.com/orangci/walls-catppuccin-mocha/master/pixel-galaxy.png"
  blur: none
cardBlur: md

theme: dark
color: gray
favicon: https://raw.githubusercontent.com/Furglitch/docker-stack/refs/heads/main/config-web/mediawiki/images/furglitch.svg
iconStyle: theme

headerStyle: boxed
layout:
  Media:
    style: row
    columns: 2
  Servarr:
    style: row
    columns: 2
  Download:
    style: row
    columns: 2

hideVersion: true
disableUpdateCheck: true